import fs from "node:fs";
import path from "node:path";
import type { SkillEntry, SkillIndex } from "./types.ts";

const DATA_DIR = path.join(process.cwd(), "data");

// ── Write index.json ────────────────────────────────────

export function writeIndex(skills: SkillEntry[]): void {
  const now = new Date().toISOString();

  // Source counts
  const sources: Record<string, number> = {};
  for (const s of skills) {
    sources[s.source] = (sources[s.source] ?? 0) + 1;
  }

  const index: SkillIndex = {
    version: "1.0.0",
    generatedAt: now,
    totalSkills: skills.length,
    totalCanonical: skills.filter((s) => s.canonical).length,
    sources,
    skills: skills.sort((a, b) => b.qualityScore - a.qualityScore),
  };

  fs.mkdirSync(DATA_DIR, { recursive: true });
  fs.writeFileSync(
    path.join(DATA_DIR, "index.json"),
    JSON.stringify(index, null, 2),
  );
  console.log(`[output] index.json: ${index.totalSkills} skills (${index.totalCanonical} canonical)`);
}

// ── Write index-by-category.json ─────────────────────────

export function writeCategoryIndex(skills: SkillEntry[]): void {
  const byCategory: Record<string, SkillEntry[]> = {};
  for (const s of skills.filter((s) => s.canonical)) {
    const cat = s.category || "other";
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat]!.push(s);
  }

  fs.writeFileSync(
    path.join(DATA_DIR, "index-by-category.json"),
    JSON.stringify(byCategory, null, 2),
  );
  console.log(`[output] index-by-category.json: ${Object.keys(byCategory).length} categories`);
}

// ── Write changelog ─────────────────────────────────────

export function writeChangelog(skills: SkillEntry[], dateStr: string): void {
  const changelogDir = path.join(DATA_DIR, "changelog");
  fs.mkdirSync(changelogDir, { recursive: true });

  // Load previous index to compute diff
  const prevIndexPath = path.join(DATA_DIR, "index.json");
  let prevSlugs = new Set<string>();
  try {
    const prev = JSON.parse(fs.readFileSync(prevIndexPath, "utf-8")) as SkillIndex;
    prevSlugs = new Set(prev.skills.map((s) => s.slug));
  } catch {
    // First run, no previous index
  }

  const currentSlugs = new Set(skills.map((s) => s.slug));
  const added = skills.filter((s) => !prevSlugs.has(s.slug)).map((s) => s.slug);
  const removed = [...prevSlugs].filter((s) => !currentSlugs.has(s));

  const changelog = { date: dateStr, added, removed, total: skills.length };

  fs.writeFileSync(
    path.join(changelogDir, `${dateStr}.json`),
    JSON.stringify(changelog, null, 2),
  );

  if (added.length || removed.length) {
    console.log(`[output] changelog: +${added.length} -${removed.length}`);
  }
}

// ── Generate README section ─────────────────────────────

export function writeReadme(skills: SkillEntry[]): void {
  const canonical = skills.filter((s) => s.canonical);
  const byCategory: Record<string, SkillEntry[]> = {};
  for (const s of canonical) {
    const cat = s.category || "other";
    if (!byCategory[cat]) byCategory[cat] = [];
    byCategory[cat]!.push(s);
  }

  const lines: string[] = [
    "# GetSkill Index",
    "",
    `> Auto-generated skill index from ${skills.length} skills across multiple sources.`,
    `> Last updated: ${new Date().toISOString().split("T")[0]}`,
    "",
    "## Stats",
    "",
    `- **Total Skills**: ${skills.length}`,
    `- **Canonical (unique)**: ${canonical.length}`,
    `- **Categories**: ${Object.keys(byCategory).length}`,
    "",
    "## Skills by Category",
    "",
  ];

  const categoryNames: Record<string, string> = {
    "document-processing": "Document Processing",
    "web-development": "Web Development",
    design: "Design",
    "mcp-tools": "MCP Tools",
    "coding-assistance": "Coding Assistance",
    "data-analysis": "Data & Analysis",
    communication: "Communication",
    devops: "DevOps",
    research: "Research",
    other: "Other",
  };

  for (const [cat, catSkills] of Object.entries(byCategory).sort((a, b) => b[1].length - a[1].length)) {
    lines.push(`### ${categoryNames[cat] ?? cat} (${catSkills.length})`);
    lines.push("");
    for (const s of catSkills.sort((a, b) => b.qualityScore - a.qualityScore).slice(0, 50)) {
      const link = s.sourceUrl;
      const stars = s.stars ? ` ⭐${s.stars}` : "";
      lines.push(`- [**${s.name}**](${link})${stars} — ${s.description.slice(0, 100)}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Index generated by [getskill-indexer](https://github.com/GetSkill-Agent/getskill-indexer)*`);

  fs.writeFileSync(path.join(DATA_DIR, "README.md"), lines.join("\n"));
  console.log("[output] README.md updated");
}
